import json

from fastapi import FastAPI, Request, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import requests
import time
import os

#To run this project you need to be in BACKEND folder and run:
# & "C:/Program Files/Python39/python.exe" -m uvicorn main:app --reload --port 1234

app = FastAPI()

# Allow requests from your Chrome extension
app.add_middleware(
    CORSMiddleware,
    allow_origins=["chrome-extension://<YOUR_EXTENSION_ID>"],  # or ["*"] for testing
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- AI Platform Configuration ---
AI_PLATFORM_URL = 'https://agai-platform-api.dev.int.proquest.com'
AI_PLATFORM_API_KEY = 'DemoToken'
UNIQUE_PREFIX = 'UTwiz'

agent_path_segment = (UNIQUE_PREFIX).lower()

conversation_id = ''


def send_message(data):
    testrail_template = [
        {
            "title": "Login with valid credentials",
            "priority_id": 3,
            "custom_steps_separated": [
                {"content": "Enter username", "expected": "Username accepted"},
                {"content": "Enter password", "expected": "Login successful"}
            ]
        }
    ]
    BASE_DIR = os.path.dirname(__file__)
    file_path = os.path.join(BASE_DIR, "prompt.txt")

    with open(file_path, "r", encoding="utf-8") as f:
        prompt = f.read()
    # prompt = "I am a developer that need to write Unit Tests based on an Functional Specification Document."
    # "Please generate Unit Tests as JSON for TestRail based on the below Functional Specification Document."
    # "and bases on the information in this site: https://knowledge.exlibrisgroup.com/Alma"
    # "I don't want any text in addition to the JSON array."
    # "The format of the JSON is: {0}"
    # "The Functional Specification Document: ".format(testrail_template) + data['content']

    prompt = prompt.replace("{0}", data['title'])
    prompt = prompt.replace("{1}", str(testrail_template))
    prompt = prompt.replace("{2}", data['content'])
    CONV_BODY = {
  "prompt": prompt,
  "max_tokens": 10000,
  "temperature": 0.7,
  "num_results": 1,
  "streaming": False,
  "images": [],
  "image_detail": "low",
  "seed": 0,
  "response_format": {},
  "tools": [],
  "tool_choice": {},
  "top_p": -1,
  "messages": [],
  "timing_debug": False,
  "usage": False,
  "batch": False,
  "batch_file_id": "string",
  "batch_data": [
    {
      "prompt": "string",
      "images": [
        "string"
      ],
      "messages": [
        {
          "additionalProp1": {}
        }
      ]
    }
  ],
  "reasoning": "medium"
}
    response = requests.post(AI_PLATFORM_URL + '/large-language-models/gpt_4o_mini/',
                             headers={'x-auth-token': AI_PLATFORM_API_KEY}, json=CONV_BODY)

    res = response.json()['results'][0]['completion'].replace("```json", "").replace("```", "")
    res = json.loads(res)
    print(res)
    return res


def push_tests_to_testrail(tests, title):
    # === TestRail configuration ===
    TESTRAIL_BASE = "https://testrail.pre.proquest.com/testrail/index.php?/api/v2"
    USER = "Joey.Gelpe@exlibrisgroup.com"
    API_KEY = "Newemployee123"
    PROJECT_ID = "27"

    response = requests.post(
        f"{TESTRAIL_BASE}/add_section/{PROJECT_ID}",
        auth=(USER, API_KEY),
        headers={"Content-Type": "application/json"},
        json={
            "suite_id": 32713,
            "name": title,
            "description": "Auto generated by UT Wiz :)"
        }
    )
    SECTION_ID = response.json().get("id")

    # === Loop through and add each case ===
    for case in tests:
        response = requests.post(
            f"{TESTRAIL_BASE}/add_case/{SECTION_ID}",
            auth=(USER, API_KEY),
            headers={"Content-Type": "application/json"},
            json=case
        )

        if response.status_code == 200:
            data = response.json()
            print(f"✅ Created case '{data['title']}' (ID: {data['id']})")
        else:
            print(f"❌ Failed to create '{case['title']}': {response.status_code} {response.text}")

        # Avoid hitting rate limits
        time.sleep(0.3)


@app.post("/")
async def read_root(request: Request) :
    data = await request.json()
    tests = send_message(data)
    push_tests_to_testrail(tests, data['title'])
    return {"message": "UTs created successfully"}
