const TESTRAIL_URL = 'https://testrail.pre.proquest.com/testrail/index.php?/api/v2';
const GET_SUITES = 'get_suites';
const TESTRAIL_PROJECT_ID = '27';

const format = (date) => {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    return `${year}${month}`;
  }

const getSprintToSearch = () => {
  const currentDate = new Date();
  const year = currentDate.getFullYear();
  const month = currentDate.getMonth();
  return [format(new Date(year, month + 3)), format(new Date(year, month + 2)), format(new Date(year, month + 1))];
}

export class TestRailUtils {
    
    async fetchTestRailCases() {
        const sprintsToSearch = getSprintToSearch();
        return fetch(`${TESTRAIL_URL}/${GET_SUITES}/${TESTRAIL_PROJECT_ID}`, {
        method: "GET",
        headers: {
            "Authorization": "Basic " + btoa("Joey.Gelpe@exlibrisgroup.com:Newemployee123"),
            "Content-Type": "application/json"
        }
        })
      .then(res => res.json())
      .then(data =>  data.filter(suite => sprintsToSearch.some(sprint => suite.name.includes(sprint))))
      .then(data => data.sort((a, b) => a.name.localeCompare(b.name)));
    }

    async fetchTestRailSections(suiteId) {
        return fetch(`${TESTRAIL_URL}/get_sections/${TESTRAIL_PROJECT_ID}&suite_id=${suiteId}`, {
            method: "GET",
            headers: { 
                "Authorization": "Basic " + btoa("Joey.Gelpe@exlibrisgroup.com:Newemployee123"),
                "Content-Type": "application/json"
            }
        });
    }

    async getOrCreateAllTreeSection(suiteId, pathString, title) {
        const sectionsData = pathString.split("/").map(s => s.trim()).filter(Boolean);
        const sections = await this.fetchTestRailSections(suiteId).then(res => res.json()); 
        let parentId = null;
        let foundDepth = -1;

        for (let i = 0; i < sectionsData.length; i++) {
            const match = sections.filter(
                s => s.name === sectionsData[i] && s.parent_id === parentId
            );
            if (!match.length) break;
            parentId = match[0].id;
            foundDepth = i;
        }
        for (let i = foundDepth + 1; i < sectionsData.length; i++) {
            const created = await this.createTestRailSection(suiteId, sectionsData[i], parentId)
                .then(res => res.json());
            parentId = created.id;
        }
        return this.createTestRailSection(suiteId, title, parentId).then(res => res.json());
    }

    async createTestRailSection(suiteId, title, parentId = null) {
        return fetch(`${TESTRAIL_URL}/add_section/${TESTRAIL_PROJECT_ID}`, {
            method: "POST",
            headers: {
                "Authorization": "Basic " + btoa("Joey.Gelpe@exlibrisgroup.com:Newemployee123"),
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                "suite_id": suiteId,
                "name": title,
                "description": "Auto generated by UT Wiz :)",
                "parent_id": parentId
            })
        });
    }

    async postTestRailCases(sectionId, data) {
        return fetch(`${TESTRAIL_URL}/add_case/${sectionId}`, {
        method: "POST",
        headers: {
            "Authorization": "Basic " + btoa("Joey.Gelpe@exlibrisgroup.com:Newemployee123"),
            "Content-Type": "application/json"
        },
        body: JSON.stringify(data)
        });
    }
}