const TESTRAIL_URL = 'https://testrail.pre.proquest.com/testrail/index.php?/api/v2';
const GET_SUITES = 'get_suites';
const TESTRAIL_PROJECT_ID = '27';


export class TestRailUtils {
    async fetchTestRailCases() {
        return fetch(`${TESTRAIL_URL}/${GET_SUITES}/${TESTRAIL_PROJECT_ID}`, {
        method: "GET",
        headers: {
            "Authorization": "Basic " + btoa("keren.jacobson@clarivate.com:Port0585"),
            "Content-Type": "application/json"
        }
        });
    }

    async createTestRailSection(suiteId, title) {
        return fetch(`${TESTRAIL_URL}/add_section/${TESTRAIL_PROJECT_ID}`, {
            method: "POST",
            headers: {
                "Authorization": "Basic " + btoa("keren.jacobson@clarivate.com:Port0585"),
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                "suite_id": suiteId,
                "name": title,
                "description": "Auto generated by UT Wiz :)"
            })
        });
    }

    async postTestRailCases(data) {
        return fetch(`${TESTRAIL_URL}/add_section/${TESTRAIL_PROJECT_ID}`, {
        method: "POST",
        headers: {
            "Authorization": "Basic " + btoa("keren.jacobson@clarivate.com:Port0585"),
            "Content-Type": "application/json"
        },
        body: JSON.stringify(data)
        });
    }
}